name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    name: Lint & Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check formatting (StyLua)
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "2.4.1"
          args: --check src/

      - name: Install Selene
        uses: cargo-bins/cargo-binstall-action@v1

      - name: Lint (Selene)
        run: |
          cargo binstall selene --version 0.28.0 --no-confirm
          selene src/
